### ISSUE TITLE
plan for improved security in CAU

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/secLib#1]
discussion taking place on the 23rd of July.  This discussion shall include the use of blockchain

**Comment by mrsarang** [comment]
We discussed with STFC to add blockchain into the CAU, we have plan to implement and test Hyperledger/FABRIC in September as shirely mentioned in email : 

Blockchain (BC) – Both UPC and STFC are keen to push forward on adding BC to mF2C to enhance trust, security and privacy.   BC has built in features like immutable fabric to guarantee transactions integrity, transparency and auditability, use of encryption for confidentiality, plus replication for availability etc.  The initial ideas are:

a.        To create a private, permissioned BC with the CAUs (see point 5 on role) authorised to create transactions.  The CAUs and Leader CAUs will be nodes on this private blockchain. 

b.       We use the BC for key management.  We store the public keys of the fog members in the chain, we can use the key for verifying signature and to encrypt data.  The CAU leader can use its local BC for low-latency security control.  The replicated BCs facilitates inter-fog communications as public keys are replicated across the BC nodes.  If one node fails, it can be bypassed. 

Any discussion or advice can be helpful. Thanks guys

**Comment by cjdcordeiro** [comment]
shouldn't key management stay on the cloud only? after all this is something central to the full mf2c and that should be kept secure at all times...

**Comment by syc17** [comment]
I take key management as referring to the generation, use and destruction of cryptographic keys.  In mF2C, we are using PKI.  The certificates are generated by the cloud CA and distributed via the CAUs to the certificate owners.  The public keys from the certificates are used for cryptographic purposes,  they will be stored in the CAUs to facilitate low latency security control in the fog and to ensure availability (via BC's replication).  The set of public keys stored in the private BC nodes captures the fog cluster membership as transparent and immutable BC transactions.   The private keys stay with the certificate owners and are used to sign messages and to decipher incoming messages encrypted with the recipient's public key.    The CA in the cloud will manage a certificate revocation list and/or OCSP which need to be consulted by services that authenticate clients using the mF2C certificates.   Perhaps Cris has something specific in mind regarding key management?

**Comment by cjdcordeiro** [comment]
key management is about "generation, exchange, storage, use, crypto-shredding (destruction) and replacement of keys". 

I think that delegating each one of these workflows to a different component/location/role might be unmaintainable. There are open source key management tools and plenty of use cases we can learn from (example: https://aws.amazon.com/kms/). Key management should be a redundant functionality/service by itself, instead of being tied to other services like the CA, CAU or BC. 

In my opinion, key management is super important on a distributed system. If there is a key (of any kind - encryption, api, etc.) which is used widely in the same way over multiple distributed inter-connected devices, and for some reasons that key is changed (lost, renewed, compromised...) , then you need to propagate it every node. You need to be able to manage this key, and be prepared to replace it without having to recall every single device. Most importantly, these keys need to be in a safe place, and be redundant.

**Comment by mrsarang** [comment]
Hi dears,

I was thinking in like hierarchical key management, i mean some how  
cloud has over key storage distribution and generation and each cau  
act as key manager for fog area as well, i must read some more  
opensources to see if its possible? Whats yout view? Thanks
Quoting Cristovao Cordeiro <notifications@github.com>:

**Comment by syc17** [comment]
To support the policy-driven security architecture and loosely coupled security service infrastructure proposed in D3.1, STFC proposes to port the cryptography and signing functionalities out of its Security library to the CAU.  The idea is that an Agent can use its CAU-client block as the api to use these functionalities.  As the CAU 'knows' the public keys of the agents, data can be encrypted for specific recipients.  Though how to secure the communication between containers running on different host is an issue, ? overlay network?  As we are dealing with control data, I presume we don't need to worry about data streams.   Could partners please comment on this suggestion?

**Comment by cjdcordeiro** [comment]
outdated and being addressed in other tickets
