### ISSUE TITLE
define how certificates are used  in mF2c

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/secLib#2]
needed by #1

needs https://github.com/mF2C/mF2C/issues/76

**Comment by syc17** [comment]
In IT1, each (valid) agent got issued a X.509 certificate, via the CAU, by the untrust CA.  The certificate is the credential that uniquely identifies the agent in mF2C.  The hierarchy of CAUs togethers maintain a global view of the identities of these agents to facilitate trust and to enable agent mobility (between fog instances).  A CAU acts as the local key manager for the agents that it services.  Apart from identity, as per the policy-driven security design proposed in D3.1, the certificate should be used for encrypting and signing messages between agents (data in flight) to ensure confidentiality, integrity and authenticity.   The IT1 hello-world demo stopped at the new agent exchanging (certificate) keys with its leader agent and did not illustrate how the certificates would be used in securing data in flight.   Up to now, we talked about using the certificate to uniquely identifies an agent, but we have not talked about authorisation.   Do we need to control access to resources and how do we determine entitlement?

**Comment by cjdcordeiro** [comment]
https://docs.google.com/document/d/1xvsUaHbJUTqFqJG40ThazP4rhNmo8wN5SJFwYa_kA4w/edit?usp=sharing

**Comment by jjensenral** [comment]
The appropriate long-term storage for this particular item has now been determined. Description of the architecture will be in D2.7; the description of the implementation will go into D3.2, in the section for the CAU client.
