### ISSUE TITLE
discuss the need of key management

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/secLib#3]
related with #2

**Comment by syc17** [comment]
related to #1,  see comments in #1  re using block chain for key management.

**Comment by syc17** [comment]
Jens raised the question regarding the purpose of key management.  Are we thinking about managing the encryption keys for data at rest?  He feels supporting this (encrypting data at rest) would be far too complex and would incur too much efforts from mF2C's view point.    See his document on at-rest-encryption
[at-rest-encryption.docx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b4746420733320012adba65/125516c66e82c728ace21e0d46e980d7318790bdc2ecb140b644e080204929316546b3397f8fe62bab0021435a561aff130e5c4df4a88828f7be3c708c5f0dbe873f5f26d42103eee9dc4be05ce36ade0d97bcae8b44cae93826e18e88493a1f051e8ff84f78.docx)
From my own viewpoint, I feel the key management should be about managing the identities of agents in the F2C ecosystem; hence the connection with #2 and #1.

**Comment by syc17** [comment]
If we agree that mF2C key management is about managing agent identities.  Then we could make this task a sub-task of #1

**Comment by cjdcordeiro** [comment]
connected to #1 

to be discussed at the f2f meeting

**Comment by syc17** [comment]
I seem to remember that we agree not to support key management for data at rest and the CAU (STFC impl) will be used for sharing an Agent's public key.
