### ISSUE TITLE
(March 28th) deploy VPN server for mF2C

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/secLib#4]

**Comment by syc17** [comment]
Please note that at the meeting I said this needs to be consulted with Jens, I don't think you can assume that STFC is responsible for the task.

**Comment by cjdcordeiro** [comment]
the task is in your hands until further notice. If the situation changes after you speak with @jjensenral , then we need to re-discuss this

**Comment by jjensenral** [comment]
Just to note that Cris and I did discuss this but we need to do more work on investigating VPN before we can deploy a "solution". As we agreed that VPN was not super critical, we should move the deadline for this task forward to, say, some time in May.

**Comment by cjdcordeiro** [comment]
I'd actually mark it as critical because there isn't yet a networking/discovery solution for the microagent.

we were planning to do a hands-on of the microagent during the summer camp. If discovery is not present, then it will just be yet another NuvlaBox demo

**Comment by jjensenral** [comment]
OK, thanks for the feedback.  Did anyone ever document the requirements for the VPN server - like how clients authenticate to it, how it's supposed to work?
In any case I won't have time to look at it till next week. I did start looking at VPN but over the past three weeks, most of what little mF2C time I've had has gone into the blog posts for Antonio.

**Comment by cjdcordeiro** [comment]
there are no requirements so any VPN would do the job

I've decided to setup my own for the meantime

**Comment by jjensenral** [comment]
Currently testing OpenVPN using image kylemanna/openvpn (ie vpn server hosted in docker)
It builds its own PKI but we could easily replace it with our agents' PKI.

**Comment by jjensenral** [comment]
Currently using setup with agent (PKI) credentials as client authentication. Both client and server use Docker image kylemanna/openvpn.  Now I just need a piece of cloud to deploy the server in, and document the remaining setup process.

**Comment by cjdcordeiro** [comment]
cool. can you share an example of an .ovpn configuration file? and also, enable client-to-client in openvpn please

**Comment by jjensenral** [comment]
The server is deployed (the container is called 'vpnserver')  and it's working and I can set up a VPN from another container and use the server to connect out. Currently debugging the client-to-client

**Comment by jjensenral** [comment]
OK, I can confirm that it's working.  My test setup has a container running with a server and two other containers with clients; they get virtual IP addresses and can ping stuff in the outside world. And can ping each other's virtual hosts and virtual networks.
All I need now is to document how to configure the client.

**Comment by cjdcordeiro** [comment]
good.

as for the clients, they (the discovery) are expecting an .ovpn file.
