### ISSUE TITLE
(March 30th) put the inter-agent secure communication workflow in place

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/secLib#5]
STFC, please feel free to split this ticket into several ones, as this feels like an EPIC

depends on https://github.com/mF2C/mF2C/issues/77

**Comment by syc17** [comment]
decomposed into separate issues:
https://github.com/orgs/mF2C/projects/1#card-20403845
https://github.com/orgs/mF2C/projects/1#card-20403080 (done)
https://github.com/orgs/mF2C/projects/1#card-20403286 (done)
https://github.com/orgs/mF2C/projects/1#card-20402814 (done)

**Comment by syc17** [comment]
The components are in place, we need to involve LCM to test the flow.
